#!/usr/bin/env python

"""Amulet tests on a basic barbican deployment on xenial-queens for keystone v2.
"""

from basic_deployment import ManilaGenericBasicDeployment

if __name__ == '__main__':
    deployment = ManilaGenericBasicDeployment(series='xenial', keystone_version='2')
    deployment.run_tests()
