#!/usr/bin/env python

"""Amulet tests on a basic barbican deployment on bionic-rocky for keystone v3
"""

from basic_deployment import ManilaGenericBasicDeployment

if __name__ == '__main__':
    deployment = ManilaGenericBasicDeployment(
        series='bionic', keystone_version='3',
        openstack='cloud:bionic-rocky',
        source='cloud:bionic-rocky')
    deployment.run_tests()
